name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        uses: webfactory/ssh-agent@v0.5.4
        with:
          fetch-depth: 0
          ssh-private-key: ${{ secrets.LEKKO_CI_PRIVATE_KEY }}
      - name: setup-go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0
      - name: ci
        if: success()
        run: make ci
