name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LEKKO_CI_PRIVATE_KEY }}
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://lekkoci:${TOKEN}@github.com".insteadOf "https:github.com"
      - name: setup-go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0
      - name: ci
        if: success()
        run: make ci
