name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.LEKKO_CI_GITHUB_PAT }}
        run: git config --global --add url."https://lekkoci:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: ci
        if: success()
        run: make ci
